global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.0.240:9090']

  - job_name: 'mysql'
    static_configs:
      - targets: ['db:3306']